let {OS} = require('./utils');
let {TrantorNetwork} = require('trantor-js');

let MAIN_CONSTANTS = {
    DEBUG: false,
    FILE_SLASH: OS.getPathSeparator(),
    APP_DIR: OS.getHome(),
    ASAR_DIR: OS.getAsarFolder(),
    ENC_TIME: 1521388915000,
    START_BLOCK: 151946,
    UPDATING_USER: 'CSFXrbxX8SKvdMbDmDcxmNPMMTEppeUphS',
    NETWORK: TrantorNetwork.MAINNET
};

MAIN_CONSTANTS.EXTRA_DIR = MAIN_CONSTANTS.ASAR_DIR + 'extra/';
MAIN_CONSTANTS.DB_DIR = MAIN_CONSTANTS.APP_DIR + '/database/';
MAIN_CONSTANTS.IPFS_DIR = MAIN_CONSTANTS.APP_DIR + '/ipfs/';
MAIN_CONSTANTS.DBMIGRATIONS_DIR = MAIN_CONSTANTS.EXTRA_DIR + 'dbmigrations/';
MAIN_CONSTANTS.CREDENTIALS_FILE = MAIN_CONSTANTS.EXTRA_DIR + 'credentials_prod.json';
MAIN_CONSTANTS.DATABASE_CREATION_FILE = MAIN_CONSTANTS.EXTRA_DIR + 'index.db.sql';
MAIN_CONSTANTS.DATABASE_FILE = MAIN_CONSTANTS.DB_DIR + 'index.db';
MAIN_CONSTANTS.BIN_DIR = MAIN_CONSTANTS.APP_DIR + '/bin/';
MAIN_CONSTANTS.WALLET_DIR = MAIN_CONSTANTS.BIN_DIR;
MAIN_CONSTANTS.WALLET_FILE = MAIN_CONSTANTS.WALLET_DIR + 'wallet.dat';
MAIN_CONSTANTS.DATA_DIR = MAIN_CONSTANTS.APP_DIR + '/files/';
MAIN_CONSTANTS.APP_CONF_FILE = MAIN_CONSTANTS.APP_DIR + '/app_main.conf';
MAIN_CONSTANTS.BINARY_NAME = 'creativecoind' + '-' + OS.getOSTag() + OS.getExecutableExtension();
MAIN_CONSTANTS.BINARIES_URL = 'https://github.com/creativechain/creativechain-core/releases/download/v1.2.1.1/';
MAIN_CONSTANTS.DAEMON_URL = MAIN_CONSTANTS.BINARIES_URL + 'creativecoind-';
MAIN_CONSTANTS.CHECKSUMS_URL = MAIN_CONSTANTS.BINARIES_URL + 'sha256sums.txt';

let TEST_CONSTANTS = {
    DEBUG: true,
    FILE_SLASH: OS.getPathSeparator(),
    APP_DIR: OS.getHome(),
    ASAR_DIR: OS.getAsarFolder(),
    ENC_TIME: 1521388915000,
    START_BLOCK: 97000,
    UPDATING_USER: 'c6ePQcixZAAckGxjgJt18Pm2Yh8d6M2i3f',
    NETWORK: TrantorNetwork.TESTNET
};

TEST_CONSTANTS.EXTRA_DIR = TEST_CONSTANTS.ASAR_DIR + '/extra/';
TEST_CONSTANTS.DB_DIR = TEST_CONSTANTS.APP_DIR + '/database_test/';
TEST_CONSTANTS.IPFS_DIR = TEST_CONSTANTS.APP_DIR + '/ipfs_test/';
TEST_CONSTANTS.DBMIGRATIONS_DIR = TEST_CONSTANTS.EXTRA_DIR + 'dbmigrations/';
TEST_CONSTANTS.CREDENTIALS_FILE = TEST_CONSTANTS.EXTRA_DIR + 'credentials.json';
TEST_CONSTANTS.DATABASE_CREATION_FILE = TEST_CONSTANTS.EXTRA_DIR + 'index.db.sql';
TEST_CONSTANTS.DATABASE_FILE = TEST_CONSTANTS.DB_DIR + 'index.db';
TEST_CONSTANTS.BIN_DIR = TEST_CONSTANTS.APP_DIR + '/bin/';
TEST_CONSTANTS.WALLET_DIR = TEST_CONSTANTS.BIN_DIR + '/testnet3/';
TEST_CONSTANTS.WALLET_FILE = TEST_CONSTANTS.WALLET_DIR + 'wallet.dat';
TEST_CONSTANTS.DATA_DIR = TEST_CONSTANTS.APP_DIR + '/files_test/';
TEST_CONSTANTS.APP_CONF_FILE = TEST_CONSTANTS.APP_DIR + '/app.conf';
TEST_CONSTANTS.BINARY_NAME = 'creativecoind' + '-' + OS.getOSTag() + OS.getExecutableExtension();
TEST_CONSTANTS.BINARIES_URL = 'https://github.com/creativechain/creativechain-core/releases/download/v1.2.1.1/';
TEST_CONSTANTS.DAEMON_URL = TEST_CONSTANTS.BINARIES_URL + 'creativecoind-';
TEST_CONSTANTS.CHECKSUMS_URL = TEST_CONSTANTS.BINARIES_URL + 'sha256sums.txt';

if (module) {
    module.exports = {
        MainnetConstants: MAIN_CONSTANTS,
        TestnetConstants: TEST_CONSTANTS
    };
}