let {OS} = require('./utils');

let APP_MAIN_CONSTANTS = {
    DEBUG: false,
    FILE_SLASH: OS.getPathSeparator(),
    APP_DIR: OS.getHome(),
    ASAR_DIR: OS.getAsarFolder(),
    ENC_TIME: 1521388915000,
    START_BLOCK: 151946,
    UPDATING_USER: 'CSFXrbxX8SKvdMbDmDcxmNPMMTEppeUphS',
};

APP_MAIN_CONSTANTS.EXTRA_DIR = APP_MAIN_CONSTANTS.ASAR_DIR + '/extra/';
APP_MAIN_CONSTANTS.IPFS_DIR = APP_MAIN_CONSTANTS.APP_DIR + '/ipfs/';
APP_MAIN_CONSTANTS.DBMIGRATIONS_DIR = APP_MAIN_CONSTANTS.EXTRA_DIR + 'dbmigrations/';
APP_MAIN_CONSTANTS.CREDENTIALS_FILE = APP_MAIN_CONSTANTS.EXTRA_DIR + 'credentials_prod.json';
APP_MAIN_CONSTANTS.DATABASE_CREATION_FILE = APP_MAIN_CONSTANTS.EXTRA_DIR + 'index.db.sql';
APP_MAIN_CONSTANTS.BIN_DIR = APP_MAIN_CONSTANTS.APP_DIR + '/bin/';
APP_MAIN_CONSTANTS.WALLET_DIR = APP_MAIN_CONSTANTS.BIN_DIR;
APP_MAIN_CONSTANTS.WALLET_FILE = APP_MAIN_CONSTANTS.WALLET_DIR + 'wallet.dat';
APP_MAIN_CONSTANTS.DATA_DIR = APP_MAIN_CONSTANTS.APP_DIR + '/files/';
APP_MAIN_CONSTANTS.APP_CONF_FILE = APP_MAIN_CONSTANTS.APP_DIR + '/app_main.conf';

let APP_TEST_CONSTANTS = {
    DEBUG: false,
    FILE_SLASH: OS.getPathSeparator(),
    APP_DIR: OS.getHome(),
    ASAR_DIR: OS.getAsarFolder(),
    ENC_TIME: 1521388915000,
    START_BLOCK: 97000,
    UPDATING_USER: 'c6ePQcixZAAckGxjgJt18Pm2Yh8d6M2i3f',
};

APP_TEST_CONSTANTS.EXTRA_DIR = APP_TEST_CONSTANTS.ASAR_DIR + '/extra/';
APP_TEST_CONSTANTS.IPFS_DIR = APP_TEST_CONSTANTS.APP_DIR + '/ipfs-test/';
APP_TEST_CONSTANTS.DBMIGRATIONS_DIR = APP_TEST_CONSTANTS.EXTRA_DIR + 'dbmigrations/';
APP_TEST_CONSTANTS.CREDENTIALS_FILE = APP_TEST_CONSTANTS.EXTRA_DIR + 'credentials.json';
APP_TEST_CONSTANTS.DATABASE_CREATION_FILE = APP_TEST_CONSTANTS.EXTRA_DIR + 'index.db.sql';
APP_TEST_CONSTANTS.BIN_DIR = APP_TEST_CONSTANTS.APP_DIR + '/bin/';
APP_TEST_CONSTANTS.WALLET_DIR = APP_TEST_CONSTANTS.BIN_DIR + '/testnet3/';
APP_TEST_CONSTANTS.WALLET_FILE = APP_TEST_CONSTANTS.WALLET_DIR + 'wallet.dat';
APP_TEST_CONSTANTS.DATA_DIR = APP_TEST_CONSTANTS.APP_DIR + '/files_test/';
APP_TEST_CONSTANTS.APP_CONF_FILE = APP_TEST_CONSTANTS.APP_DIR + '/app.conf';

if (module) {
    module.exports = {
        MainConstants: APP_MAIN_CONSTANTS,
        TestnetConstants: APP_TEST_CONSTANTS
    };
}